name: abbert2

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - numpy
  - pandas
  - joblib
  - dask
  - distributed
  - pyarrow
  - more-itertools
  - argh
  - pip:
    - -e .
