name: abbert2

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - python
  - abnumber
  - pip
  - numpy
  - pandas
  - joblib
  - pyarrow
  - tqdm
  - more-itertools
  - requests
  - argh
  - smart_open
  - python-xxhash
  - anarci==2020.04.23

  # For cerebras
  - pyyaml
  - tensorflow>=2.3

  - pip:
    - -e .
