name: abbert2

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - numpy
  - pandas
  - joblib
  - pyarrow
  - tqdm
  - more-itertools
  - requests
  - argh
  - smart_open
  - python-xxhash
  - anarci==2020.04.23
  - pip:
    - -e .
