import numpy as np
import pytest

from abbert2.oas.preprocessing import parse_anarci_status, _preprocess_anarci_data

# --- ANARCI status parsing

ANARCI_STATUS_EXPECTATIONS = [
    (
        '|Deletions: 1, 2||Missing Conserved Cysteine: 23|Shorter than IMGT defined: fw1|',
        {
            'deletions': np.array([1, 2], dtype=np.uint8),
            'missing_conserved_cysteine': True,
            'fw1_shorter_than_imgt_defined': True
        }
    ),

    (
        '|Deletions: 1, 2|||Shorter than IMGT defined: fw1|CDR3 is over 37 aa long',
        {
            'deletions': np.array([1, 2], dtype=np.uint8),
            'fw1_shorter_than_imgt_defined': True,
            'cdr3_is_over_37_aa_long': True,
        }
    ),

    (
        "['Missing Conserved Cysteine 23 or 104', 'fw1 is shorter than IMGT defined']",
        {
            'missing_conserved_cysteine': True,
            'fw1_shorter_than_imgt_defined': True
        }
    ),

    (
        "['Unusual amino acid: X27', 'Unusual amino acid: X38', 'fw1 is shorter than IMGT defined']",
        {
            'unusual_residue': True,
            'fw1_shorter_than_imgt_defined': True
        }
    ),

    (
        "['fw1 is shorter than IMGT defined', 'fw4 is shorter than IMGT defined']",
        {
            'fw1_shorter_than_imgt_defined': True,
            'fw4_shorter_than_imgt_defined': True
        }
    ),

    (
        "['Unusual amino acid: X57', 'fw1 is shorter than IMGT defined']",
        {
            'unusual_residue': True,
            'fw1_shorter_than_imgt_defined': True,
        }
    ),

    (
        "['Insertion: 44A', 'Insertion: 44B']",
        {
            'insertions': ['44A', '44B'],
        }
    ),

    (None, {}),
]


@pytest.mark.parametrize('status,expected', ANARCI_STATUS_EXPECTATIONS)
def test_parse_anarci_status(status, expected):
    np.testing.assert_equal(parse_anarci_status(status), expected)


# --- ANARCI data preprocessing

ANARCI_DATA_EXPECTATIONS = [
    ({
         'locus': 'H',
         'expected_cdr3': 'ARGLLGRFLEWWTTEGYGMDV',
         'anarci_status': '|Deletions: 10, 73||||',
         'numbering_data_dict': {'fwh1': {'1 ': 'Q',
                                          '11 ': 'E',
                                          '12 ': 'V',
                                          '13 ': 'K',
                                          '14 ': 'K',
                                          '15 ': 'P',
                                          '16 ': 'G',
                                          '17 ': 'A',
                                          '18 ': 'S',
                                          '19 ': 'V',
                                          '2 ': 'V',
                                          '20 ': 'K',
                                          '21 ': 'V',
                                          '22 ': 'S',
                                          '23 ': 'C',
                                          '24 ': 'K',
                                          '25 ': 'A',
                                          '26 ': 'S',
                                          '3 ': 'Q',
                                          '4 ': 'L',
                                          '5 ': 'V',
                                          '6 ': 'Q',
                                          '7 ': 'S',
                                          '8 ': 'G',
                                          '9 ': 'A'},
                                 'cdrh1': {'27 ': 'G',
                                           '28 ': 'Y',
                                           '29 ': 'T',
                                           '30 ': 'F',
                                           '35 ': 'T',
                                           '36 ': 'S',
                                           '37 ': 'Y',
                                           '38 ': 'G'},
                                 'fwh2': {'39 ': 'I',
                                          '40 ': 'S',
                                          '41 ': 'W',
                                          '42 ': 'V',
                                          '43 ': 'R',
                                          '44 ': 'Q',
                                          '45 ': 'A',
                                          '46 ': 'P',
                                          '47 ': 'G',
                                          '48 ': 'Q',
                                          '49 ': 'G',
                                          '50 ': 'L',
                                          '51 ': 'E',
                                          '52 ': 'W',
                                          '53 ': 'M',
                                          '54 ': 'G',
                                          '55 ': 'W'},
                                 'cdrh2': {'56 ': 'I',
                                           '57 ': 'S',
                                           '58 ': 'A',
                                           '59 ': 'Y',
                                           '62 ': 'N',
                                           '63 ': 'G',
                                           '64 ': 'N',
                                           '65 ': 'T'},
                                 'fwh3': {'100 ': 'A',
                                          '101 ': 'V',
                                          '102 ': 'Y',
                                          '103 ': 'Y',
                                          '104 ': 'C',
                                          '66 ': 'N',
                                          '67 ': 'Y',
                                          '68 ': 'A',
                                          '69 ': 'Q',
                                          '70 ': 'K',
                                          '71 ': 'L',
                                          '72 ': 'Q',
                                          '74 ': 'G',
                                          '75 ': 'R',
                                          '76 ': 'V',
                                          '77 ': 'T',
                                          '78 ': 'M',
                                          '79 ': 'T',
                                          '80 ': 'T',
                                          '81 ': 'D',
                                          '82 ': 'T',
                                          '83 ': 'S',
                                          '84 ': 'T',
                                          '85 ': 'S',
                                          '86 ': 'T',
                                          '87 ': 'A',
                                          '88 ': 'Y',
                                          '89 ': 'M',
                                          '90 ': 'E',
                                          '91 ': 'L',
                                          '92 ': 'R',
                                          '93 ': 'S',
                                          '94 ': 'L',
                                          '95 ': 'R',
                                          '96 ': 'S',
                                          '97 ': 'D',
                                          '98 ': 'D',
                                          '99 ': 'T'},
                                 'cdrh3': {'105 ': 'A',
                                           '106 ': 'R',
                                           '107 ': 'G',
                                           '108 ': 'L',
                                           '109 ': 'L',
                                           '110 ': 'G',
                                           '111 ': 'R',
                                           '111A': 'F',
                                           '111B': 'L',
                                           '111C': 'E',
                                           '111D': 'W',
                                           '112 ': 'G',
                                           '112A': 'E',
                                           '112B': 'T',
                                           '112C': 'T',
                                           '112D': 'W',
                                           '113 ': 'Y',
                                           '114 ': 'G',
                                           '115 ': 'M',
                                           '116 ': 'D',
                                           '117 ': 'V'},
                                 'fwh4': {'118 ': 'W',
                                          '119 ': 'G',
                                          '120 ': 'Q',
                                          '121 ': 'G',
                                          '122 ': 'T',
                                          '123 ': 'T',
                                          '124 ': 'V',
                                          '125 ': 'T',
                                          '126 ': 'V',
                                          '127 ': 'S',
                                          '128 ': 'S'}
                                 }
     },
     {
         'anarci_cdr3_is_over_37_aa_long': False,
         'anarci_deletions': np.array([10, 73], dtype=np.uint8),
         'anarci_fwr1_shorter_than_imgt_defined': False,
         'anarci_fwr4_shorter_than_imgt_defined': False,
         'anarci_insertions': None,
         'anarci_missing_conserved_cysteine': False,
         'anarci_unusual_residue': False,
         'cdr1_length': 8,
         'cdr1_start': 25,
         'cdr2_length': 8,
         'cdr2_start': 50,
         'cdr3_length': 21,
         'cdr3_start': 96,
         'fwr1_length': 25,
         'fwr1_start': 0,
         'fwr2_length': 17,
         'fwr2_start': 33,
         'fwr3_length': 38,
         'fwr3_start': 58,
         'fwr4_length': 11,
         'fwr4_start': 117,
         'has_insertions': True,
         'has_kappa_gap_21': False,
         'has_mutated_conserved_cysteines': False,
         'has_unexpected_insertions': False,
         'has_wrong_cdr3_reconstruction': False,
         'imgt_insertions': ['',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             'A',
                             'B',
                             'C',
                             'D',
                             'D',
                             'C',
                             'B',
                             'A',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             '',
                             ''],
         'imgt_positions': np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14,
                                     15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                                     28, 29, 30, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
                                     45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
                                     58, 59, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
                                     74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
                                     87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99,
                                     100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 111,
                                     111, 111, 111, 112, 112, 112, 112, 112, 113, 114, 115, 116, 117,
                                     118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128], dtype=np.uint8),
         'sequence_aa': 'QVQLVQSGAEVKKPGASVKVSCKASGYTFTSYGISWVRQAPGQGLEWMGWISAYNGNTNYAQKLQGRVTMTTDTSTS'
                        'TAYMELRSLRSDDTAVYYCARGLLGRFLEWWTTEGYGMDVWGQGTTVTVSS'
     }),
]


@pytest.mark.parametrize('parameters,expected', ANARCI_DATA_EXPECTATIONS)
def test_preprocess_anarci_data(parameters, expected):
    # noinspection PyArgumentList,PyTypeChecker
    np.testing.assert_equal(_preprocess_anarci_data(**parameters), expected)
